# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/madduxv/programming/cpp/R3000_Emu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/madduxv/programming/cpp/R3000_Emu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/madduxv/programming/cpp/R3000_Emu/CMakeFiles /Users/madduxv/programming/cpp/R3000_Emu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/madduxv/programming/cpp/R3000_Emu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named r3000_emu

# Build rule for target.
r3000_emu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r3000_emu
.PHONY : r3000_emu

# fast build rule for target.
r3000_emu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/build
.PHONY : r3000_emu/fast

src/assembler/asminstruction.o: src/assembler/asminstruction.cpp.o
.PHONY : src/assembler/asminstruction.o

# target to build an object file
src/assembler/asminstruction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/asminstruction.cpp.o
.PHONY : src/assembler/asminstruction.cpp.o

src/assembler/asminstruction.i: src/assembler/asminstruction.cpp.i
.PHONY : src/assembler/asminstruction.i

# target to preprocess a source file
src/assembler/asminstruction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/asminstruction.cpp.i
.PHONY : src/assembler/asminstruction.cpp.i

src/assembler/asminstruction.s: src/assembler/asminstruction.cpp.s
.PHONY : src/assembler/asminstruction.s

# target to generate assembly for a file
src/assembler/asminstruction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/asminstruction.cpp.s
.PHONY : src/assembler/asminstruction.cpp.s

src/assembler/assembler.o: src/assembler/assembler.cpp.o
.PHONY : src/assembler/assembler.o

# target to build an object file
src/assembler/assembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/assembler.cpp.o
.PHONY : src/assembler/assembler.cpp.o

src/assembler/assembler.i: src/assembler/assembler.cpp.i
.PHONY : src/assembler/assembler.i

# target to preprocess a source file
src/assembler/assembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/assembler.cpp.i
.PHONY : src/assembler/assembler.cpp.i

src/assembler/assembler.s: src/assembler/assembler.cpp.s
.PHONY : src/assembler/assembler.s

# target to generate assembly for a file
src/assembler/assembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/assembler.cpp.s
.PHONY : src/assembler/assembler.cpp.s

src/assembler/lexer.o: src/assembler/lexer.cpp.o
.PHONY : src/assembler/lexer.o

# target to build an object file
src/assembler/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/lexer.cpp.o
.PHONY : src/assembler/lexer.cpp.o

src/assembler/lexer.i: src/assembler/lexer.cpp.i
.PHONY : src/assembler/lexer.i

# target to preprocess a source file
src/assembler/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/lexer.cpp.i
.PHONY : src/assembler/lexer.cpp.i

src/assembler/lexer.s: src/assembler/lexer.cpp.s
.PHONY : src/assembler/lexer.s

# target to generate assembly for a file
src/assembler/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/lexer.cpp.s
.PHONY : src/assembler/lexer.cpp.s

src/assembler/parser.o: src/assembler/parser.cpp.o
.PHONY : src/assembler/parser.o

# target to build an object file
src/assembler/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/parser.cpp.o
.PHONY : src/assembler/parser.cpp.o

src/assembler/parser.i: src/assembler/parser.cpp.i
.PHONY : src/assembler/parser.i

# target to preprocess a source file
src/assembler/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/parser.cpp.i
.PHONY : src/assembler/parser.cpp.i

src/assembler/parser.s: src/assembler/parser.cpp.s
.PHONY : src/assembler/parser.s

# target to generate assembly for a file
src/assembler/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/parser.cpp.s
.PHONY : src/assembler/parser.cpp.s

src/assembler/symbols.o: src/assembler/symbols.cpp.o
.PHONY : src/assembler/symbols.o

# target to build an object file
src/assembler/symbols.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/symbols.cpp.o
.PHONY : src/assembler/symbols.cpp.o

src/assembler/symbols.i: src/assembler/symbols.cpp.i
.PHONY : src/assembler/symbols.i

# target to preprocess a source file
src/assembler/symbols.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/symbols.cpp.i
.PHONY : src/assembler/symbols.cpp.i

src/assembler/symbols.s: src/assembler/symbols.cpp.s
.PHONY : src/assembler/symbols.s

# target to generate assembly for a file
src/assembler/symbols.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/assembler/symbols.cpp.s
.PHONY : src/assembler/symbols.cpp.s

src/emulator/cpu.o: src/emulator/cpu.cpp.o
.PHONY : src/emulator/cpu.o

# target to build an object file
src/emulator/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/cpu.cpp.o
.PHONY : src/emulator/cpu.cpp.o

src/emulator/cpu.i: src/emulator/cpu.cpp.i
.PHONY : src/emulator/cpu.i

# target to preprocess a source file
src/emulator/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/cpu.cpp.i
.PHONY : src/emulator/cpu.cpp.i

src/emulator/cpu.s: src/emulator/cpu.cpp.s
.PHONY : src/emulator/cpu.s

# target to generate assembly for a file
src/emulator/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/cpu.cpp.s
.PHONY : src/emulator/cpu.cpp.s

src/emulator/emulator.o: src/emulator/emulator.cpp.o
.PHONY : src/emulator/emulator.o

# target to build an object file
src/emulator/emulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/emulator.cpp.o
.PHONY : src/emulator/emulator.cpp.o

src/emulator/emulator.i: src/emulator/emulator.cpp.i
.PHONY : src/emulator/emulator.i

# target to preprocess a source file
src/emulator/emulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/emulator.cpp.i
.PHONY : src/emulator/emulator.cpp.i

src/emulator/emulator.s: src/emulator/emulator.cpp.s
.PHONY : src/emulator/emulator.s

# target to generate assembly for a file
src/emulator/emulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/emulator.cpp.s
.PHONY : src/emulator/emulator.cpp.s

src/emulator/instructions.o: src/emulator/instructions.cpp.o
.PHONY : src/emulator/instructions.o

# target to build an object file
src/emulator/instructions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/instructions.cpp.o
.PHONY : src/emulator/instructions.cpp.o

src/emulator/instructions.i: src/emulator/instructions.cpp.i
.PHONY : src/emulator/instructions.i

# target to preprocess a source file
src/emulator/instructions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/instructions.cpp.i
.PHONY : src/emulator/instructions.cpp.i

src/emulator/instructions.s: src/emulator/instructions.cpp.s
.PHONY : src/emulator/instructions.s

# target to generate assembly for a file
src/emulator/instructions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/instructions.cpp.s
.PHONY : src/emulator/instructions.cpp.s

src/emulator/memory.o: src/emulator/memory.cpp.o
.PHONY : src/emulator/memory.o

# target to build an object file
src/emulator/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/memory.cpp.o
.PHONY : src/emulator/memory.cpp.o

src/emulator/memory.i: src/emulator/memory.cpp.i
.PHONY : src/emulator/memory.i

# target to preprocess a source file
src/emulator/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/memory.cpp.i
.PHONY : src/emulator/memory.cpp.i

src/emulator/memory.s: src/emulator/memory.cpp.s
.PHONY : src/emulator/memory.s

# target to generate assembly for a file
src/emulator/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/emulator/memory.cpp.s
.PHONY : src/emulator/memory.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r3000_emu.dir/build.make CMakeFiles/r3000_emu.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... r3000_emu"
	@echo "... src/assembler/asminstruction.o"
	@echo "... src/assembler/asminstruction.i"
	@echo "... src/assembler/asminstruction.s"
	@echo "... src/assembler/assembler.o"
	@echo "... src/assembler/assembler.i"
	@echo "... src/assembler/assembler.s"
	@echo "... src/assembler/lexer.o"
	@echo "... src/assembler/lexer.i"
	@echo "... src/assembler/lexer.s"
	@echo "... src/assembler/parser.o"
	@echo "... src/assembler/parser.i"
	@echo "... src/assembler/parser.s"
	@echo "... src/assembler/symbols.o"
	@echo "... src/assembler/symbols.i"
	@echo "... src/assembler/symbols.s"
	@echo "... src/emulator/cpu.o"
	@echo "... src/emulator/cpu.i"
	@echo "... src/emulator/cpu.s"
	@echo "... src/emulator/emulator.o"
	@echo "... src/emulator/emulator.i"
	@echo "... src/emulator/emulator.s"
	@echo "... src/emulator/instructions.o"
	@echo "... src/emulator/instructions.i"
	@echo "... src/emulator/instructions.s"
	@echo "... src/emulator/memory.o"
	@echo "... src/emulator/memory.i"
	@echo "... src/emulator/memory.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

